# ifplugstatus
# Autogenerated from man page /usr/share/man/man8/ifplugstatus.8.gz
complete -c ifplugstatus -s a -l auto -d 'Enable interface automatically before querying (default: off)'
complete -c ifplugstatus -s h -l help -d 'Show help'
complete -c ifplugstatus -s q -l quiet -d 'Decrease verbosity by one'
complete -c ifplugstatus -s v -l verbose -d 'Increase verbosity by one.  See option -q'
complete -c ifplugstatus -s V -l version -d 'Show version  RETURN VALUES 0 Success'

