# msmtpd
# Autogenerated from man page /usr/share/man/man1/msmtpd.1.gz
complete -c msmtpd -l version -d 'Print version information'
complete -c msmtpd -l help -d 'Print help'
complete -c msmtpd -l inetd -d 'Start single SMTP session on stdin/stdout'
complete -c msmtpd -l interface -d 'Listen on the given IPv6 or IPv4 address instead of 127. 0. 0. 1'
complete -c msmtpd -l port -d 'Listen on the given port number instead of 25'
complete -c msmtpd -l log -d 'Set logging: none (default), syslog, or logging to the given file'
complete -c msmtpd -l command -d 'Pipe mails to cmd instead of msmtp'
complete -c msmtpd -l auth -d 'Require authentication with this user name'

