# twm
# Autogenerated from man page /usr/share/man/man1/twm.1.gz
complete -c twm -o clientId -d 'Each time twm starts, it calls SmcOpenConnection to establish a new session'
complete -c twm -o display -d 'Specify the X server to use'
complete -c twm -o file -d 'Specify the name of the startup file to use'
complete -c twm -o quiet -d 'Tells twm that it should not print error messages when it receives unexpected…'
complete -c twm -o restore -d 'When twm\'s session is stopped, it attempts to save the current window configu…'
complete -c twm -o single -d 'Tells twm that only the default screen (as specified by -display or by the DI…'
complete -c twm -o verbose -d 'Tells twm that it should print error messages whenever it receives an unexpec…'
complete -c twm -s V -d 'Tell twm to print its version to the standard output, and exit'

